package com.rodentcontrol.customer;
import android.app.AlertDialog;
import android.content.Intent;import android.os.Bundle;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import java.util.concurrent.Executors;
public class LoginActivity extends AppCompatActivity{
 EditText user,pass;TextView msg; Button login,forgot;
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_login);user=findViewById(R.id.username);pass=findViewById(R.id.password);msg=findViewById(R.id.message);login=findViewById(R.id.login);forgot=findViewById(R.id.forgot);login.setOnClickListener(v->login());forgot.setOnClickListener(v->forgotPassword());}
 void login(){String u=user.getText().toString().trim(),p=pass.getText().toString();if(u.isEmpty()||p.isEmpty()){msg.setText("Vui lòng nhập tài khoản và mật khẩu.");return;}setBusy(true);Executors.newSingleThreadExecutor().execute(()->{try{org.json.JSONObject r=Api.login(u,p,"Customer Android");SecureStore.putToken(this,r.getString("token"));runOnUiThread(()->{setBusy(false);startActivity(new Intent(this,MainActivity.class));finishAffinity();});}catch(Exception e){runOnUiThread(()->{setBusy(false);msg.setText(error(e));});}});}
 void forgotPassword(){ final EditText email=new EditText(this);email.setHint("Email đã đăng ký trên Web Admin");email.setInputType(33); new AlertDialog.Builder(this).setTitle("Quên mật khẩu").setMessage("Nhập email tài khoản khách hàng để nhận mã 6 số.").setView(email).setNegativeButton("Hủy",null).setPositiveButton("Gửi mã",(d,w)->requestCode(email.getText().toString().trim())).show(); }
 void requestCode(String email){if(email.isEmpty()){msg.setText("Vui lòng nhập email.");return;}msg.setText("Đang gửi mã...");Executors.newSingleThreadExecutor().execute(()->{try{Api.forgotPassword(email);runOnUiThread(()->showReset(email));}catch(Exception e){runOnUiThread(()->msg.setText(error(e)));}});}
 void showReset(String email){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);int p=24;box.setPadding(p,p,p,p);EditText code=new EditText(this);code.setHint("Mã 6 số");code.setInputType(2);EditText pw=new EditText(this);pw.setHint("Mật khẩu mới (ít nhất 8 ký tự)");pw.setInputType(129);EditText pw2=new EditText(this);pw2.setHint("Nhập lại mật khẩu mới");pw2.setInputType(129);box.addView(code);box.addView(pw);box.addView(pw2);new AlertDialog.Builder(this).setTitle("Đặt lại mật khẩu").setMessage("Mã có hiệu lực 15 phút.").setView(box).setNegativeButton("Hủy",null).setPositiveButton("Đổi mật khẩu",(d,w)->{String a=pw.getText().toString(),b=pw2.getText().toString();if(a.length()<8||!a.equals(b)){msg.setText("Mật khẩu không hợp lệ hoặc không trùng nhau.");return;}Executors.newSingleThreadExecutor().execute(()->{try{Api.resetPassword(email,code.getText().toString().trim(),a);runOnUiThread(()->msg.setText("Đổi mật khẩu thành công. Bạn có thể đăng nhập lại."));}catch(Exception e){runOnUiThread(()->msg.setText(error(e)));}});}).show();}
 void setBusy(boolean x){login.setEnabled(!x);forgot.setEnabled(!x);if(x)msg.setText("Đang xác thực...");}
 String error(Exception e){return e.getMessage()==null?"Không kết nối được máy chủ.":e.getMessage();}
}
